### ISSUE TITLE
Check if user has Undertale

### ISSUE THREAD

**Issue by gunvirranu** [bolt2strike/Undertale-Save-Manager#3]
You might wanna check if the user actually has Undertale.
I don't have the game but I tried running it anyway.
It created an empty `UNDERTALE` folder in `AppData\Local`.
It also created an empty backup in `Undertale Backups`.

**Comment by bolt2strike** [comment]
Resolved, 

https://github.com/bolt2strike/Undertale-Save-Manager/commit/c81559c05e71cb29a9705f26eda313d8f5910ac2
