### ISSUE TITLE
Add feature to delete current save game

### ISSUE THREAD

**Issue by bolt2strike** [bolt2strike/Undertale-Save-Manager#5]

**Comment by gunvirranu** [comment]
Does this nuke all the files? If it does, great. If not, then that should be a feature as well. 
So you can completely start the game over easily.

**Comment by bolt2strike** [comment]
That's exactly what it does. It's implemented now. https://github.com/bolt2strike/Undertale-Save-Manager/commit/14d39f2e07c9ce301c9601beb10641f72d4ebb1d
