### ISSUE TITLE
Custom game locations

### ISSUE THREAD

**Issue by gunvirranu** [bolt2strike/Undertale-Save-Manager#6]
Is there a way to have custom game locations? Because not everyone is going to have the game on their C:\ drive for example. If there isn't, could you consider that?

**Comment by bolt2strike** [comment]
The save location on Windows is **always** in the same place. The executable however is not. If I knew where to find the executable (I could guess) then I could have a button to launch the game, and maybe a few other things. But as far as the save location is concerned unless it's on a mac I know the save location is fixed to C:/Users/<Your User>/AppData/Local/UNDERTALE

Thanks for the suggestion though.
