### ISSUE TITLE
You can bundle icon with jar and exe

### ISSUE THREAD

**Issue by gunvirranu** [bolt2strike/Undertale-Save-Manager#7]
You can bundle the icon with the jar and exe so it doesn't need to be in the Distribution folder.
I don't know which software you're using to make the exe, but I know for a fact that you can do it because I have in the past (using Launch4j).
In case this is already implemented, then you might wanna take the icon.ico out of the Distribution folder.

**Comment by bolt2strike** [comment]
Resolved. https://github.com/bolt2strike/Undertale-Save-Manager/commit/b79c9c750e04bd1d833239b16eebb8911d0930b3

Thanks
